default:
  image: node:lts
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

stages:
  - start
  - test

start:
  stage: start
  script:
    - echo "Starting pipeline"

run_tests:
  stage: test
  script:
    - npm test

format_check:
  stage: test
  script:
    - npm run format-check
