workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "dev"

default:
  image: node:lts
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

stages:
  - start
  - test
  - deploy

start:
  stage: start
  script:
    - echo "Starting pipeline"

run_tests:
  stage: test
  script:
    - npm test

format_check:
  stage: test
  script:
    - npm run format-check

lint_check:
  stage: test
  script:
    - npm run lint

njsscan:
  stage: test
  image: python
  cache:

  before_script:
    - pip3 install --upgrade njsscan
  script:
    - njsscan .
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
    - if: $CI_COMMIT_BRANCH == "master"
  allow_failure: true

github-deploy:
  stage: deploy
  inherit:
    default: false
    variables: true
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  image: registry.gitlab.com/feup-tbs/ldso2021/t4g2/github-deploy:1.0.0
  variables:
    GIT_STRATEGY: none
  script:
    - gh repo clone node-red-contrib-self-healing
    - cd node-red-contrib-self-healing
    - gh pr create -R jpdias/node-red-contrib-self-healing -B master -t "Integrate changes from LDSO T4G2 group" -b "Check the CHANGELOG.md file for more details"

docker-deploy-dev:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  image: docker:19.03.13
  services:
    - docker:19.03.13-dind
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PW
  script:
    - docker build -t ldso2020t4g2/node-red-contrib-self-healing:next .
    - docker push ldso2020t4g2/node-red-contrib-self-healing:next

docker-deploy-prod:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  image: docker:19.03.13
  services:
    - docker:19.03.13-dind
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PW
  script:
    - docker build -t ldso2020t4g2/node-red-contrib-self-healing:latest .
    - docker push ldso2020t4g2/node-red-contrib-self-healing:latest
