version: "3.7"

services:
  node-red-one:
    build:
      context: ../
    environment:
      - TZ=Europe/Lisbon
    ports:
      - "8001:1880"
    volumes:
      - ./data/node-red-data:/data
    links:
      - mqtt
      - node-red-two
      - node-red-three
    privileged: true

  node-red-two:
      build:
        context: ../
      environment:
        - TZ=Europe/Lisbon
      ports:
        - "8002:1880"
      volumes:
        - ./data/node-red-data:/data
      links:
        - mqtt
        - node-red-three
      privileged: true

  node-red-three:
    build:
      context: ../
    environment:
      - TZ=Europe/Lisbon
    ports:
      - "8003:1880"
    volumes:
      - ./data/node-red-data:/data
    links:
      - mqtt
    privileged: true

  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./data/mosquitto-data/config/:/mosquitto/config/
    ports:
      - "12345:1883"
    restart: always
    
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer_data:/data